import { useState, useRef } from 'react'
import './App.css'

function App() {
  const [selectedFile, setSelectedFile] = useState(null)
  const [previewUrl, setPreviewUrl] = useState(null)
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const fileInputRef = useRef(null)

  const handleFileSelect = (e) => {
    const file = e.target.files[0]
    if (file) {
      setSelectedFile(file)
      setPreviewUrl(URL.createObjectURL(file))
      setResult(null)
      setError(null)
    }
  }

  const handleDrop = (e) => {
    e.preventDefault()
    const file = e.dataTransfer.files[0]
    if (file) {
      setSelectedFile(file)
      setPreviewUrl(URL.createObjectURL(file))
      setResult(null)
      setError(null)
    }
  }

  const handleDragOver = (e) => {
    e.preventDefault()
  }

  const analyzeImage = async () => {
    if (!selectedFile) return

    setLoading(true)
    setError(null)

    const formData = new FormData()
    formData.append('file', selectedFile)

    try {
      const response = await fetch('http://localhost:8000/predict', {
        method: 'POST',
        body: formData,
      })

      if (!response.ok) {
        throw new Error('Failed to analyze image. Please ensure the backend is running.')
      }

      const data = await response.json()
      if (data.error) {
        throw new Error(data.error)
      }
      setResult(data)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="container">
      <header className="app-header">
        <div className="logo">
          <span>🫁</span> PneumoScan AI
        </div>
        <p>Advanced Chest X-Ray Analysis System</p>
      </header>

      <main>
        <div className="glass-card">
          <div className="upload-section">
            <h2>X-Ray Diagnostic Tool</h2>
            <p>Upload a pediatric chest X-ray to detect signs of pneumonia using our simplified VGG model and DHE enhancement.</p>

            <div
              className={`drop-zone ${selectedFile ? 'active' : ''}`}
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onClick={() => fileInputRef.current.click()}
            >
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileSelect}
                accept="image/*"
                hidden
              />
              <div className="upload-icon">📤</div>
              <p>{selectedFile ? selectedFile.name : "Drag & drop or click to upload X-ray"}</p>
            </div>

            {previewUrl && (
              <div className="image-preview">
                <img src={previewUrl} alt="X-ray Preview" />
              </div>
            )}

            <button
              className="analyze-button"
              onClick={analyzeImage}
              disabled={!selectedFile || loading}
            >
              {loading ? <div className="loader"></div> : "Start Analysis"}
            </button>

            {error && <p style={{ color: 'var(--error-color)', marginTop: '1rem' }}>{error}</p>}
          </div>
        </div>

        {result && (
          <div className="glass-card result-card">
            <h3>Diagnostic Results</h3>
            <div className={`status-badge ${result.prediction === 'Pneumonia' ? 'status-pneumonia' : 'status-normal'}`}>
              {result.prediction}
            </div>

            <p>Confidence Level: {(result.confidence * 100).toFixed(2)}%</p>

            <div className="confidence-bar-container">
              <div
                className="confidence-bar"
                style={{ width: `${result.confidence * 100}%` }}
              ></div>
            </div>

            <p className="text-secondary" style={{ fontSize: '0.9rem' }}>
              This result is generated by an AI model and should be reviewed by a qualified medical professional.
            </p>
          </div>
        )}

        <div className="info-grid">
          <div className="info-item">
            <h3>🔍 Dynamic Hist. Eq. (DHE)</h3>
            <p>We apply DHE to enhance the contrast of grayscale X-rays, making it easier to identify consolidation and infiltrates in the lung fields.</p>
          </div>
          <div className="info-item">
            <h3>🧠 Simplified VGG Architecture</h3>
            <p>Based on Electronics 2021, our 6-layer CNN is specifically optimized for medical imaging without the overhead of heavy ImageNet weights.</p>
          </div>
          <div className="info-item">
            <h3>📊 High Accuracy</h3>
            <p>Targeting ~96% accuracy and 0.99 AUC, the system provides reliable screening for pediatric pneumonia symptoms.</p>
          </div>
        </div>
      </main>

      <footer style={{ marginTop: '3rem', padding: '2rem', textAlign: 'center', opacity: 0.6 }}>
        <p>© 2026 Medical Imaging Research Lab | Electronics 2021 Implementation</p>
      </footer>
    </div>
  )
}

export default App
